FROM aflplusplus/aflplusplus:latest

RUN mkdir /app/
WORKDIR /app/
RUN git clone https://github.com/brainflow-dev/brainflow.git
WORKDIR /app/brainflow/
RUN git checkout -b before_patch bfbcaa5afbb84522f5f2a52fba87ed13965cae49 
RUN mkdir build
WORKDIR /app/brainflow/build
RUN cmake -DCMAKE_CXX_COMPILER=afl-clang-fast++ ..
RUN make -j16 Brainflow
ENV AFL_I_DONT_CARE_ABOUT_MISSING_CRASHES=1
ENV AFL_AUTORESUME=1
ADD harness.cpp /app/brainflow/build
ADD Makefile_2 /app/brainflow/build/
ADD test.cpp /app/brainflow/build/
RUN cat Makefile_2 >> Makefile
RUN make -j16  test_brain
RUN make -j16  test_harness
ADD ./fuzz.sh /app/brainflow/build/
RUN mkdir crashers
RUN echo -ne "MQkxCjkJMQkxCTIKMQo=" | base64 -d > crashers/14_byte
RUN echo -ne "MjIyMnIJMrLNAQAAADMyMjIUMwozMjIzTQ0y8j0yMg4x8n8KMk/NMjNSMh3SMjIyzcx/MSwxMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyIDIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMkQyMjIyMjIyMjIyMjIyMjJIMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyOTIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMs0qczIyzc0yzcwxLDHz8/Pz88weMSwx8nIJMjLNzcwyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMj0yMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjLycgkyMs3NzBEyzcMxzc3NtVIyzTMoRVUyTQ4xcgoyMs0OMfJyCjIyMlIyzDIpABAAAMMNLDHoAwoAAAEAzTIsMzExLDNDMSwzMTLO0zHycgoyMs3NzDIyzTMyMjIyMg4x8nIKMjIzzTPNzc0x8nKAMnIKM7LNMjNSMjIzUjIyMjIyzc3MHjEsMfJyCTIyzc0yzTIzMjIyFDIyM00NMvI9MjIOMfJyCjJrzTIzUjIcMjL///9/HoUsMfJyCTIyzc3METLNEDHNzc21UjLNMyhFVTJNDjFyCjIyzQ4x8nIKMjIfMjLMMjIAEAAAww0sMegDCjIqzc3NMiwzMTEsM0cxLDMxMs7TMfJyCjIyz83MMjLNMzIyMjIyDjHycgoyMjPNM83NzTIyzTMyMjIyMg4x8nIKMjIzMjKNCjIyzTL/CwozMzEOMTIE/zIyMjLNKpUyMs3NMs3MMSwx8/Pz8/PycgoyAAQAAM3MHjEsMQ1yCTIyzc3METLNwzHNzcG1XzLNMgAzUjIyMjIyzc3MHjEsMfJyCQEyzc3VETLN8nKCcizNznMyMjIyMs3MMjIyxM3NMjIxN84NLDHycgoyMs3NzDIyzTMyMjIyMhAx8nLqMjIzADMxMv//CgozMzEOMTIE/woKM1IyMjIyMs3NM+ExLDHycgkxMTExMTExMTExATExMTExMTExMTExMTExMTExzs4xMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMSwzLDMxMwoyzZSUlJSUlJSUMjIyMswyMjIyMvfDDSwx6AMKMjLNzc0yMs0zMjIyAQP1zc0yzc0yMs0zMjIyATIOMTEsMzExLABAztPM+jEsM87TIiwzMQAALAAAAMzNzTLMMjIyRjIOMfJyMjLNMzIyMjIyDjHycgoyMjMyMo0KMjLNMv8KCjMzMQ4xMgT/MjIyMs0qczIyzc0yzcwxLDHz8/Pz88weMSwx8nIJMjLNzcwRCg==" | base64 -d > crashers/1186_python_crasher
ADD brainoverflow.py /app/brainflow/build/
RUN wget https://bootstrap.pypa.io/get-pip.py
RUN python get-pip.py
RUN rm get-pip.py
RUN pip install brainflow pandas
CMD sh -c "/bin/bash"

